### ISSUE TITLE
QScintilla can't find sip files

### ISSUE THREAD

**Issue by JakobDev** [flathub/com.riverbankcomputing.PyQt.BaseApp#6]
I'm trying to port jdTextEdit to the BaseApp. The current manifest can be found [here](https://github.com/flathub/com.gitlab.JakobDev.jdTextEdit). jdTextEdit uses [QScintilla](https://pypi.org/project/PyQt6-QScintilla/) which is a text editor widget. It is also from Riverbank Computing.

This is the Manifest I'm working with:
```yaml
app-id: com.gitlab.JakobDev.jdTextEdit
runtime: org.kde.Platform
runtime-version: "6.2"
sdk: org.kde.Sdk
base: com.riverbankcomputing.PyQt.BaseApp
base-version: "6.2"
command: jdTextEdit
cleanup-commands:
  - /app/cleanup-BaseApp.sh
build-options:
  env:
    - BASEAPP_REMOVE_PYWEBENGINE=1
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --share=network
  - --socket=cups
  - --device=dri
  - --share=ipc

modules:
  - python3-modules.json

  - name: qscintilla-pyqt6
    buildsystem: simple
    build-commands:
      - sip-install
        --target-dir=/app/lib/3.9/site-packages/
        --verbose
        --debug
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/b6/18/fd56926545e12571ee421861da0ac257b7ce4c96388ae949a32595762f1b/PyQt6_QScintilla-2.13.2.tar.gz
        sha256: 9ffe5583200e4d6ce6c3348a4e66faf5ae081046f8b5c75ad6681546bdf2464c
        x-checker-data:
            type: pypi
            name: PyQt6-QScintilla
            packagetype: sdist

  - name: enchant
    config-opts:
      - --disable-static
      - --with-hunspell
      - --with-myspell-dir=/usr/share/hunspell
    sources:
      - type: archive
        url: https://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz
        sha256: 2fac9e7be7e9424b2c5570d8affe568db39f7572c10ed48d4e13cddf03f7097f
      - type: shell
        commands:
          - cp -p /usr/share/automake-*/config.{sub,guess} .
          - autoreconf -vfi;
    post-install:
      - install -p -D -m 0644 "COPYING.LIB" -t "${FLATPAK_DEST}/share/licenses/enchant/";
    cleanup:
      - /bin

  - name: jdTextEdit
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
      - install -Dm644 jdTextEdit/Logo.svg /app/share/icons/hicolor/scalable/apps/com.gitlab.JakobDev.jdTextEdit.svg
      - install -Dm644 deploy/com.gitlab.JakobDev.jdTextEdit.desktop /app/share/applications/com.gitlab.JakobDev.jdTextEdit.desktop
      - install -Dm644 deploy/com.gitlab.JakobDev.jdTextEdit.metainfo.xml /app/share/metainfo/com.gitlab.JakobDev.jdTextEdit.metainfo.xml
    sources:
      - type: git
        url: https://gitlab.com/JakobDev/jdTextEdit.git
        tag: "10.0"
```

When trying to build I get this error:
```
Running: sip-install --target-dir=/app/lib/3.9/site-packages/ --verbose --debug
Querying qmake about your Qt installation...
/usr/bin/qmake -query
These bindings will be built: Qsci.
Generating the Qsci bindings...
sip-install: /run/build/qscintilla-pyqt6/sip/qscimodcommon.sip: line 42 column 9: 'QtCore/QtCoremod.sip' could not be found
/run/build/qscintilla-pyqt6/sip/qscimodcommon.sip: line 43 column 9: 'QtGui/QtGuimod.sip' could not be found
/run/build/qscintilla-pyqt6/sip/qscimodcommon.sip: line 44 column 9: 'QtWidgets/QtWidgetsmod.sip' could not be found
/run/build/qscintilla-pyqt6/sip/qscimodcommon.sip: line 46 column 6: 'PyQt_Printer' is not a known qualifier
/run/build/qscintilla-pyqt6/sip/qsciprinter.sip: line 21 column 6: 'PyQt_Printer' is not a known qualifier
Error: module qscintilla-pyqt6: Der Kindprozess wurde mit Status 1 beendet
```

For some reason, it can't find the sip files.

The cleanup.sh contains this lines:
```sh
# pyqt
rm -rfv ${FLATPAK_DEST}/lib/python*/site-packages/PyQt5/bindings
rm -rfv ${FLATPAK_DEST}/share/qt
```
The cleanup.sh, which this lines who remove the bindings folder with the sip files is executed after the Build. This means, that the sip files must be present during build. I also found nothing else in the BaseApp that could remove the sip files.

I have no idea why it doesn't find the sip files.
